// AUTO-GENERATED: every exercise -> a real local image (illustrated GIF / photo).
export const EXERCISE_GIF: Record<string, string> = {
  "Standard Push-Ups": "3216-7E06s6d.gif",
  "Band Chest Press (Slow 5s)": "0989-c16nYGA.gif",
  "Pike Push-Ups": "3662-XPUDTt7.gif",
  "Band Squats": "web/sq_band.gif",
  "Sumo Squats": "web/sq_sumo.gif",
  "Band Glute Bridge": "web/glutebridge.gif",
  "Walking Lunges": "3655-J9zIWig.gif",
  "Standing Calf Raises": "1373-bJYHBIN.gif",
  "Sit-Ups": "0001-2gPfomN.gif",
  "Plank Hold": "3544-5VXmnV5.gif",
  "Band Russian Twist": "1011-S1JXDAG.gif",
  "Flutter Kicks": "0459-UVo2Qs2.gif",
  "Leg Raises": "2963-weoDEpH.gif",
  "Chin Tucks": "1403-x2chWLO.gif",
  "Lying Neck Curl": "1403-x2chWLO.gif",
  "Side Neck Flexion": "1403-x2chWLO.gif",
  "Band Lateral + Front Raise": "0977-sTg7iys.gif",
  "Band Overhead Shoulder Press": "0997-peAeMR3.gif",
  "Wrist Curls (Band)": "0994-Ezpnw9d.gif",
  "Reverse Wrist Curls (Band)": "0994-Ezpnw9d.gif",
  "Chin Tuck Hold": "1403-x2chWLO.gif",
  "Tongue Press Neck Curl": "1403-x2chWLO.gif",
  "Band Seated Row": "0990-DKBwJrL.gif",
  "Band Face Pull": "web/facepull.gif",
  "Band Bent-Over Row": "0988-km0sQC0.gif",
  "Band Deadlift": "1009-kuMiR2T.gif",
  "Band Bicep Curl": "0968-3omWx6P.gif",
  "Band Hammer Curl": "web/hammercurl.gif",
  "Pulse Squats": "web/sq_pulse.gif",
  "Single-Leg Glute Bridge": "web/sl_bridge.gif",
  "Side Plank Hold": "3544-5VXmnV5.gif",
  "Single Leg Calf Raise Hold": "1373-bJYHBIN.gif",
  "Banded Hip Thrust (Floor)": "web/hipthrust.gif",
  "Banded Romanian Deadlift": "1009-kuMiR2T.gif",
  "Banded Single-Leg Glute Bridge": "web/sl_bridge.gif",
  "Push-Ups (Band Across Back)": "0975-ufaxB52.gif",
  "Banded Chest Press (3-1-3 Tempo)": "0989-c16nYGA.gif",
  "Banded Overhead Press": "1012-u4bAmKp.gif",
  "Banded Lateral Raise (Slow)": "0977-sTg7iys.gif",
  "Banded Overhead Triceps Extension": "0998-obe5LMq.gif",
  "Banded Bent-Over Row (Wide Grip)": "0988-km0sQC0.gif",
  "Banded Seated Row (Squeeze Hold)": "0990-DKBwJrL.gif",
  "Banded Straight-Arm Pulldown": "web/strarmpull.gif",
  "Banded Bicep Curl (Slow)": "0968-3omWx6P.gif",
  "Banded Goblet Squat": "web/sq_band.gif",
  "Bulgarian Split Squat (Banded)": "0987-arsYEd3.gif",
  "Banded Sumo Squat (2s Pause)": "web/sq_sumo.gif",
  "Banded Calf Raise (Slow)": "0999-9JprnPh.gif",
  "Banded Bicep Curl — 21s Method": "0968-3omWx6P.gif",
  "Banded Hammer Curl": "web/hammercurl.gif",
  "Banded Triceps Pushdown": "0998-obe5LMq.gif",
  "Banded Triceps Kickback": "0998-obe5LMq.gif",
  "Banded Wrist Curl Superset": "0994-Ezpnw9d.gif",
  "Banded Chest Fly": "0993-sTfvVsG.gif",
  "Push-Ups (High Rep, Easy Pace)": "3216-7E06s6d.gif",
  "Band Jab-Cross": "web/jabcross.gif",
  "Band Jab-Cross Rounds": "web/jabcross.gif",
  "Band Hook Punch": "web/hook.gif",
  "Band Uppercut": "web/uppercut.gif",
  "Light Shadowboxing": "web/shadowbox.gif",
  "Band Lateral Walk": "web/latwalk.gif",
  "Banded Lateral Walks": "web/latwalk.gif",
  "Band Good Mornings": "web/goodmorning.gif",
  "Banded Good Morning": "web/goodmorning.gif",
  "Banded Standing Glute Kickback": "web/glutekickback.gif",
  "Banded Lying Hamstring Curl": "web/hamcurl.gif",
  "Banded Pec & Shoulder Stretch": "web/pecstretch.gif",
  "Full-Body Band Stretch": "web/fullstretch.gif",
  "Downward Dog to Cobra Flow": "web/yogaflow.gif",
  "Jaw Release": "web/jaw.gif",
  "Single Leg Balance Hold": "web/balance.gif",
  "Standing Leg Swings (Front/Back)": "web/legswingfb.gif",
  "Standing Leg Swings (Side to Side)": "web/legswingside.gif",
  "Front Kick": "web/kickfront.gif",
  "Front Kick (Fast)": "web/kickfront.gif",
  "Roundhouse Kick": "web/kickround.gif"
};
